/*
#------------------------------------------------------------------------------
# PROJECT EULER
# PROBLEM 2
#------------------------------------------------------------------------------
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, 
# find the sum of the even-valued terms.
#------------------------------------------------------------------------------
# SOLUTION: 4613732
#------------------------------------------------------------------------------
*/

#include <iostream>
using namespace std;

int main(){
    int save = 0;
    int prev = 0;
    int next = 1;
    int sum = 0;
    while(next < 4000000){
        save = prev;
        prev = next;
        next += save;
        sum += next % 2 == 0 ? next : 0;
    }
    cout << sum << endl;
}
