/*
#------------------------------------------------------------------------------
# PROJECT EULER
# PROBLEM 44
#------------------------------------------------------------------------------
# Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten
# pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
# 70  22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
# difference is pentagonal and D = |Pk  Pj| is minimised; what is the value
# of D?
#------------------------------------------------------------------------------
# SOLUTION: 5482660
#------------------------------------------------------------------------------
*/

#include <iostream>
#include <cmath>
#include <new>
using namespace std;

bool isPentagonal(int);

const int N = 10000;
int* pent = new int[N];

int main(){
	for(int i = 1; i <= N; i++){
		pent[i-1] = i*(3*i-1)/2;;
	}
	for(int i = 0; i < N; i++){
		for(int j = i+1; j < N; j++){
			int d = pent[j] - pent[i];
			int s = pent[j] + pent[i];
			if(isPentagonal(d) && isPentagonal(s)) cout << d << endl;
		}
	}
	return 0;
}

bool isPentagonal(int n){
	int i = sqrt((2*n)/3);
	while(pent[i] <= n && i < N){
		if(pent[i++] == n) return true;
	}
	return false;
}
